---
abstract: 'do use_ok for modules in search path'
author:
  - 'Takatoshi Kitano <kitano.tk@gmail.com>'
build_requires:
  File::Spec: 0
  FindBin::libs: 0
  Module::Install::AuthorTests: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LoadAllModules
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  List::MoreUtils: 0
  Module::Pluggable::Object: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
